name: tmwp
channels:
  - conda-forge
dependencies:
  - docx2txt
  - PyPDF2
  - aiohttp
  - pysocks
  - geopy
  - googletrans
  - cchardet
  - nest-asyncio
  - pdf2image
  - tesseract
  - pandas
  - jupyter
  - nltk
  - bs4
  - parse
  - beautifulsoup4
  - spacy
  - spacy-model-en_core_web_md
  - newspaper3k
  - pip
  - pip:
    - requests-html
    - afinn
    - vaderSentiment
    - twint
    - pyocr
